#基础设置
site_name: 北门观测站 #站点名
site_url: https://kitty-in-github.github.io/starlight_recording/ #默认站点地址

#markdown扩展语法
markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

#站点主题
theme:
  name: material

#设置分级页面
nav: 
  - 主页: index.md
  - 教程: test.md
  - 故事: 
    - 示例: story/example.md
  - 势力介绍: 
    - 索拉: power introduce/solar.md
    - 莫汝拉: power introduce/Morula.md
    - 罅隙星域: power introduce/CrackSpace.md
  - 人物: 
    - 罗拉瓦: character/Lorava.md
    - 丹佶: character/Dan Ji.md
  - 星球:
    - 索拉: 
      - 天定甲二: planet/solar/TianDingFirstNo2.md
  - 科技:
    - 遗产: 
      - 金丝黄玉双龙冕: technology/heritage/GoldDoubleGragonCrown.md
  - 奇观:
    - 破碎之城: wonder/City of The Broken.md
    - 血肉之城: wonder/City of Fresh.md
    - 太空长城: wonder/SpaceGreatWall.md